version: 2.1

description: |
  Utilities for the Swift programming language
  See this orb's source: https://github.com/CircleCI-Public/swift-orb

examples:
  standard-swift-project:
    description: |
      This orb can help you lint your Swift projects, storing output
      as CircleCI artifacts and test results
    usage:
      version: 2.1

      orbs:
        swift: circleci/swift@1.0.0

      workflows:
        build-and-test:
          jobss:
            - swift/lint

commands:
  swiftlint:
    description: "Runs swiftlint on the current directory"
    parameters:
      reportFile:
        type: string
        default: result.xml
    steps:
      - run: swiftlint lint --reporter junit | tee << parameters.reportFile >>
      - store_artifacts:
        path: << parameters.reportFile >>
      - store_test_results:
        path: << parameters.reportFile >>

jobs:
  lint:
    description: Run `swiftlint` over the repository.
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - swiftlint